name: CI/CD Spring Boot Microservices

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build-and-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      ###########################################
      #       BUILD SPRING BOOT MICROSERVICES   #
      ###########################################

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build all JARs
        run: mvn clean install -DskipTests

      ###########################################
      #              BUILD FRONTEND             #
      ###########################################

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      ###########################################
      #                DOCKER SETUP             #
      ###########################################

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      ###########################################
      #        BUILD & PUSH MICROSERVICES       #
      ###########################################

      - name: Build and push backend images
        run: |
          for service in api-gateway product-service order-service inventory-service notification-service discovery-service; do
            echo "Building and pushing $service..."
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$service:latest ./$service
            docker push ${{ secrets.DOCKER_USERNAME }}/$service:latest
          done

      ###########################################
      #          BUILD & PUSH FRONTEND          #
      ###########################################

      - name: Build and push frontend image
        run: |
          echo "Building and pushing frontend..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
